extends Node

var sentencesIntroduction = [
	["Juge", "Aujourd’hui, le tribunal déclare « nom de sa femme » officiellement décédée !"], #Commence à 1
	["Héros P", "C’est ce qu’à déclarée le juge le jour de sa septième année de la disparition de ma femme. Lors de l’annonce, j’étais complément anéantie…"],
	["Héros P", "Après avoir mis autant d’effort pour la retrouvée. Comme-ci tout cela n’avais servis à rien..."],
	["Héros P", "Mais, même avec cette nouvelle, au fond de moi, je reste sûr d’une chose, c’est qu’elle ait quelque part !"],
	["", "Après le verdict, je décida de passer une dernière fois sur son lieu de travail."],
	["Héros P", "Cela faisait un moment que je n’avais pas mis les pieds ici."],
	["Héros P", "Allons dans la salle où elle menait ses expériences."],
	["Héros P", "Cette salle n’a pas changer en sept ans. Comme-ci le temps c’était figée à cette endroit. Étant sûr que la maîtresse des lieux allait revenir pour continuer son travail."],
	["Héros P", "Visitons un dernière fois cette pièce."], #sentence 9
	["Héros P", "Emplacement 1"],
	["Héros P", "Emplacement 2"],
	["Héros P", "Emplacement 3"],
	["", "*Bruit de porte qui s'ouvre*"],
	["Amie F", "Je m’excuse, mais personne n’est autorisé à rentrée dans cette salle. Ah ! C’est toi !"],
	["Amie F", "Cela faisait longtemps ! Comment vas-tu depuis la dernière fois qu’on c’est vu?"], #sentence 15
	["Héros P", "On va dire que ça peut aller."],
	["Amie F", "Je suppose que tu as entendu la nouvelle sur la disparition de « Nom de sa femme » du tribunal..."],
	["Héros P", "Oui, j’y étais tout ta l’heure…"],
	["Amie F", "…"],
	["Héros P", "C’est pour ça que je suis ici. Je me suis promis de passer à autre chose si je ne la retrouvais pas avant cette date fatidique. On va dire que je fais en quelque sorte mes adieux en venant une dernière fois là où elle travaillait."],
	["Amie F", "Même si tu le sais déjà mais elle restera toujours une amie et même la meilleurs que j’ai eu pour moi. Je n’ai peut-être pas autant souffert que toi mais je t’assure que sa disparition du jour au lendemain ma fait beaucoup de mal. Je tenais énormément à elle."],
	["Héros P", "Je n’en doute pas une seconde. Sinon, j’aimerais encore te remercier pour toute l’aide que tu as pu m’apporter depuis sa disparition. Tu t’es considérablement impliquer dans les différents recherches et ça, je ne l’oublierais pas."],
	["Amie F", "Pas besoin de me remercier, c’était normal pour moi de participer. Si tu ne l’avais pas fait, je ne serais pas rester assises les bras croisées pour aller à sa recherche."],
	["Amie F", "Maintenant, tu vas pouvoir faire son deuil et passer à autre chose. Je pense que si elle était encore là, c’est ce qu’elle aurait voulue. "],
	["Héros P", "Je vais essayer. Cela ne va pas être facile, je te l’accorde."],
	["Héros P", "A part ça, pas trop compliquer en ce moment au boulot ?"],
	["Amie F", "Comme d’habitude, « nom du chef du labo » nous fait bosser comme des tarés en étant persuader qu’on va enfin faire une découverte dans pas longtemps. Cela fait maintenant 7 ans qui n’a pu fait de découverte majeur, alors il mets la pression à son équipe."],
	["Héros P", "Haha ! Courage à toi. Tu sais où je peux le trouver ?"],
	["Amie F", "Oui, il est dans son bureau. Tu te souviens du chemin ?"],
	["Héros P", "Oui, je m’en souviens. Je te laisse. Bonne journée à toi !"],
	["Amie F", "Bonne journée à toi aussi ! Tu as mon numéro si tu as besoin de parler à quelqu’un."],
	["Héros P", "C’est parti. Direction le bureau de « nom du chef du labo »."], #sentence 33
	["Héros P", "Excusez-moi ! Monsieur « nom du chef du labo » vous êtes-là ?"],
	["Chef de lab", "Je suis occupé ! Si vous n’avez pas rendez-vous avec moi, aller en prendre un avec ma secrétaire."],
	["Héros P", "C’est « nom du personnage principal », le mari de « nom de sa femme »."],
	["Chef de lab", "Oh ! Excusez-moi, je n’avais pas reconnu votre voix. Cela fait longtemps que vous n’étiez pas venu. Entrer ! Je vous en pris !"],
	["Héros P", "Merci de me donner un peu de votre temps."],
	["Chef de lab", "Vous savez ce qu’on dit « la science n’attends pas » ! Mais pour vous, je peux faire une exception. J’imagine que vous avez eu la nouvelle du verdict de ce matin. Toute mes condoléances pour votre femme."],
	["Héros P", "Vous saviez pour ma femme ?"],
	["Chef de lab", "Bien sûrs ! Bien que je n’ai pas pu vous aider dans les recherches que vous avez menée pour essayer de la retrouvée de part mon travail. Je n’ai de cesse de rester informer sur cette disparition. Au cas où un détail m’aurait permis de me rappeler de quelque chose d’important."],
	["Chef de lab", "Vous savez, votre femme, madame « nom de sa femme » était une des meilleurs scientifique au sein de ce laboratoire de recherche. Retrouver une femme aussi talentueuse sera difficile. J’aurais pas pu espérer pire que sa disparition soudaine aussi jeune. Elle avait un avenir prometteur devant elle."],
	["Chef de lab", "C’est grâce à elle que j’ai pu remporté le prix Nobel, il y a de cela sept ans. Après une de ces découverte majeurs, nous avons pu en comprendre plus sur les ondes gravitationnelles. Ce qui m’a permis d’en détecter une et ensuite prouver qu’elles existe bel et bien. "],
	["Chef de lab", "Einstein les avait prédits, il y a 107 ans. J’ai prouvé sa théorie. Rien de plus extraordinaire de pouvoir inscrit mon nom auprès du scientifique le plus éminent de toute la physique. Je n’aurais pas pu espérer un meilleur futur pour ma carrière mais surtout pour ma vie de scientifique."],
	["Héros P", "Vous me dit que sans elle, vous n’aurais pas pu avoir ce prix Nobel ?"],
	["Chef de lab", "Exactement ! C’est pour cela que j’aurais voulu la remercier en personne mais hélas cela ne pourra pas ce faire. Pour tout vous dire, après la nouvelle du verdict, j’avais décider de renommé la salle où elle travaillait à son nom afin de ce souvenir de sa mémoire et du travail qu’elle a accomplie ici. C’est dire de l’estime que je tiens pour elle."],
	["Héros P", "Vous ferais ça ?"],
	["Chef de lab", "Évidemment ! C’est le minimum que je puis faire. Pardonnez mon impolitesse, j’ai monopolisé toute la parole. Mais quel bon vent vous amène ici ?"],
	["Héros P", "C’était pour vous prévenir que je ne reviendrais plus ici. J’ai décidé d’avancer dans ma vie et d’arrêter les recherches."],
	["Chef de lab", "Une décision qui a dû être difficile à prendre mais qui est fort sage."],
	["Héros P", "Comme vous le dites…  Je vous remercie de m’avoir pu me laisser venir ici autant que je le souhaite. J’espère que vous ferais de nouvelles découvertes intéressantes."],
	["Chef de lab", "Ha Ha ! Bien sûrs ! Ma carrière n’est pas fini ! C’est compliqué mais on s’accroche. Sachez que vous êtes toujours le bienvenu ici. Si cela vous dérange pas, il est l’heure de rentrer chez moi."],
	["Héros P", "Il est déjà si tard ! Je n’ai pas vu l’heure passé moi."],
	["Héros P", "Puis-je vous demandez une dernière faveurs avant de vous partiez ?"],
	["Chef de lab", "Si cela rentre dans mes compétences, aucun soucis."],
	["Héros P", "J’aimerais resté encore un peu avant de partir, es-ce-que c’est possible ?"],
	["Chef de lab", "Si c’est votre dernière fois ici, cela me pose pas de problème. Étant normalement la dernière personne à partir, je ferme à clef le laboratoire. Voici mon trousseau de clef. Quand vous en aurez fini, n’oubliez pas de fermer la porte derrière vous."],
	["", "Trousseau de clef ajoutée à l’inventaire"],
	["Héros P", "Compter sur moi !"],
	["Chef de lab", "En tout cas, j’aurais besoin que vous me rendiez mon trousseau demain. Déposez le au bureau de ma secrétaire. Elle sera que c’est pour moi."],
	["Héros P", "S’en faute. Monsieur « nom du chef du labo ». Je vous souhaite une bonne fin de journée."],
	["Chef de lab", "De même ! Au revoir."],
	["Héros P", "Très bien. Je vais faire le tour une dernière fois."], #sentence 63
	["", "Quelques minutes plus tard."],
	["Héros P", "Je pense avoir fait le tour. Il est l’heure de rentrer à la maison. Ne pas oublier de fermer la porte en sortant."],
	["", "*Bruit de porte qui s'ouvre*"],
	["Héros P", "Tiens ? Peut-être monsieur « nom du chef du labo » a oublier quelque chose. Je vais pouvoir lui rendre son trousseau tout de suite comme ça."],
	["Héros P", "Monsieur …"],
	["Héros P", "Qui-est cette fille ?"],
	["Héros P", "Qui êtes-vous ? Vous n’avez pas le droit d’être ici !"],
	["Héros S", "Euh.. Excusez-moi… Vous êtes bien M.« nom du personnage principal » ?"],
	["Héros P", "Pourquoi je répondrais à cette question ?"],
	["Héros S", "…"],
	["Héros P", "Pourquoi sort-elle un papier et un téléphone de sa poche ?"],
	["", "*Bruit de sonnerie de téléphone*"],
	["Héros P", "C’est la sonnerie de mon téléphone !"],
	["Héros S", "Vous êtes bien M.« nom du personnage principal »."],
	["Héros P", "Comment connaissez-vous mon numéro ?!"],
	["Héros S", "C’est écrit sur l’avis de recherche. « Si vous avez des informations même les plus infimes à propos de cette femme, appelait M.« nom du personnage principal » au numéro ci-contre »."],
	["Héros P", "C’est bien mon avis de recherche que j’ai placardé au 4 coins de la ville. Peut-être que je ferais mieux de l’écouter."],
	["Héros P", "Oui, vous avez gagné ! Je suis bien M.« nom du personnage principal ». Que me voulez-vous ?"],
	["Héros S", "Je viens vous voir car j’ai des informations sur la personne en photo sur l’avis de recherche."],
	["Héros P", "Il manquait plus que ça… Moi, qui voulait faire mon deuil tranquillement en sortant d’ici et passer à autre chose. Comme-ci le destin voulait me faire souffrir car j’ai pris la décision d’arrêter les recherches."],
	["Héros P", "Quels types d’informations avez-vous à propos d’elle ?"],
	["Héros S", "Pour tout vous dire… je… je l’ai vu…"],
	["Héros P", "Pardon ? Vous… l’avez vu ? Où ça exactement ?"],
	["Héros S", "Ici même dans ce bâtiment."],
	["Héros P", "Quand ?! A quel moment ?! Il y a 7 ans ?! 3 ans ?! Récemment ?! Parler ?! Dites-moi !"],
	["Héros S", "Aujourd’hui…"],
	["Héros S", "Impossible ! Tout bonnement impossible ! Qu’es-ce-qui passe ? Une parfaite inconnue est en train de me dire qu’elle a vu ma femme aujourd’hui dans ce bâtiment alors que je viens d’en faire le tour. Des détails ! Il me faut des détails !"],
	["Héros P", "Elle t-elle vivante ?! Dites-moi quelle est vivante !"],
	["Héros S", "Désolé mais… j’ai vu son corps allonger par terre. Je préfère ne pas vous donner de faux espoir mais d’après ce que j’ai vu, je pense qu’elle est morte."],
	["Héros P", "Donc elle suggère qu’il y a une éventualité pour que le corps de ma femme soit ici depuis 7 ans et que je m’en sois jamais aperçu ? Non ! Quelqu’un est en train de me faire une mauvaise blague et veut me faire souffrir. Je ne vois pas d’autre possibilité !"],
	["Héros P", "Vous me mentez ! Vous êtes juste là pour me faire souffrir !"],
	["Héros S", "Non ! Je vous jure que je l’ai vu ! Il faut que vous me croyez ! Vous êtes ma dernière chance !"],
	["Héros P", "Il n’y a qu’un seul moyen pour que je vous croie. Amener-moi au corps de ma femme. Tant que je n’aurais pas vu le corps, je ne vous ferais pas confiance."],
	["Héros S", "…"],
	["Héros S", "Très bien, suivez-moi."],
	["Héros P", "C’est donc ici qu’elle a trouver le corps. Heureusement que j’ai les clefs de M.« nom du chef du labo » sinon je n’aurais pas pu entré."],
	["Héros P", "HS, où est le corps de ma femme ?"],
	["Héros S", "Par ici, M.« nom du personnage principal »."],
	["", "Je suivis HS. Nous marchâmes quelques minutes avant d’arriver à notre destination. Ce fût les minutes les plus longues de ma vie. Mon cœur n’arrêter pas de s’emballer de plus en plus vite au fur et à mesure qu’on se rapprochait. "],
	["Héros S", "Nous y voilà."],
	["Héros S", "Le corps de votre femme se trouve là-bas. (En pointant du doigt la direction qu’elle indiquait)"],
	["", "Je tourna la tête et regarda dans la direction que pointait HS. Mais à ma plus grande déception, je ne vît rien."],
	["Héros P", "HS excuse-moi mais il n’y a rien. Je ne vois pas le corps de ma femme."],
	["Héros S", "Pourquoi ? Pourquoi personne n’arrive à voir ce que je vois..."],
	["Héros P", "Hé ! HS ! Tu es sourde ou quoi ! Je te dis que je ne vois pas le corps de ma femme !"],
	["", "HP agrippa fermement les épaules de HS et la regardant droit dans les yeux."],
	["Héros P", "C’est quoi ton problème ?! Tu m’as fait venir ici pour te foutre de moi, c’est ça ?!"],
	["Héros S", "Non ! Pas du tout !"],
	["Héros P", "Tu crois que j’ai pas assez souffert après toute ces années ! Me faire de croire que ma femme est morte alors qu’il y a encore une chance qu’elle soit en vie ! Sa t’amuse ?!"],
	["Héros S", "J’ai pensé que comme s’était votre femme, vous pourrez la voir comme moi je la vois."],
	["Héros P", "Qu’es-ce-que tu racontes ?! Les fantômes ça n’existe pas ! Et puis qu’es que tu arrives à voir ? Cela peux très bien ne pas être elle ! Comment puis-je te croire alors que je ne vois rien ?!"],
	["Héros S", "Elle porte un collier en forme de trou noir."],
	["", "HP s’arrêta net."],
	["Héros P", "Impossible ! Comment elle connaît ce détail ? Je lui ai offert juste avant sa disparition. Elle n’a pas pu le voir, non plus sur la photo de l’avis de recherche, elle ne le portait pas. Comment ?!"],
	["Héros P", "Que ce qu’il vient de ce passer ?"],
	["Héros P", "« Nom de sa femme » !"],
	["Héros P", "Je l’ai vu ! Elle était là ! Allongé sur le sol ! Comment c’est possible ?"],
	["Héros S", "Alors vous aussi vous l’avez vu ! Vous voyez bien que je ne vous avez pas menti !"],
	["Héros P", "Dis-moi, quand j’ai vu le corps, ma vision était devenu bleu. Toi aussi, ça te fait pareil ?"],
	["Héros S", "Oui ! Quand je me concentre, ma vision devient aussi bleu et je peux la voir."],
	["Héros P", "Il faut juste que je me concentre j’arriverai à refaire venir ma vision bleu ?"],
	["Héros S", "Je ne sais pas. C’est la première fois que je vois une autre personne arriver à utilisé le même pouvoir que moi. Mais cela ne coûte rien de réessayer !"],
	["", "HP pris une grande inspiration puis ouvrir les yeux et se concentra pour refaire venir sa vision bleu."],
	["Héros P", "Je n’y arrive pas ! Pourquoi ?! "],
	["Héros P", "Je suis tout proche de revoir « Nom de sa femme » . Mais aussi, d’en apprendre plus sur sa disparition. C’est pas le moment de flancher, il faut que j’arrive à refaire cette vision bleu quoi qu’il en coûte ! Réfléchi ! Réfléchi ! Que faisais tu quand la vision c’est déclenché ? Rappel toi ! Aller !"],
	["Héros P", "Mais oui ! Ma vision c’est estompé quand je l’ai lâché."],
	["Héros P", "HS donne moi la main."],
	["Héros S", "Pardon ? Euh… C’est assez gênant vous voyez…"],
	["Héros P", "Bon, si ça te gêne tant. Pose là sur mon épaule alors."],
	["", "HS leva son bras et le posa sur l’épaule de HP."],
	["Héros S", "Vous pensez que cela va changer quelque chose ?"],
	["Héros P", "Tais-toi, je dois me concentrer."],
	["Héros P", "Yeah !!! J’ai réussi ! La vision bleu est revenu."],
	["Héros S", "Super ! Je peux retirer ma main maintenant ?"],
	["Héros P", "Non. J’ai besoin que l’on soit en contact pour que cela fonctionne. Tout en gardant ta main accroché à moi, on va s’approcher du corps pour que je puisse l’examiner de plus près."],
	["Héros S", "D’accord. Je vous lâcherais quand vous me le direz."],#sentence 138
	
]

# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
